#!/usr/bin/env bash
# KEEP — bootstrap a /knowledge layer in a repo.
# Idempotent: refuses to overwrite an existing /knowledge directory.
#
# Usage:
#   ./init.sh [repo-root]
#
# Defaults to current working directory if no argument is given.
# After scaffolding, prints the next-step prompt to run /keep-compile for
# ingestion if pre-existing docs were detected.

set -euo pipefail

REPO_ROOT="${1:-$(pwd)}"
REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"  # resolve to absolute path

if [[ ! -d "$REPO_ROOT" ]]; then
    echo "error: $REPO_ROOT is not a directory" >&2
    exit 1
fi

KNOWLEDGE="$REPO_ROOT/knowledge"

# ---------- 1. Refuse to overwrite ----------
if [[ -d "$KNOWLEDGE" ]]; then
    echo "error: $KNOWLEDGE already exists. KEEP refuses to overwrite." >&2
    echo "       If you want to start fresh, move it out of the way first." >&2
    exit 1
fi

# ---------- 2. Scaffold ----------
mkdir -p "$KNOWLEDGE/docs/specs"
mkdir -p "$KNOWLEDGE/docs/decisions"
mkdir -p "$KNOWLEDGE/ideas"
cat > "$KNOWLEDGE/INDEX.md" <<'EOF'
# /knowledge INDEX (auto-generated, do not edit)

This file is regenerated by `scripts/build_index.py` from YAML frontmatter on
every `/keep-compile` run. Hand-edits are reverted.

Run `/keep-compile` after creating any spec, ADR, or idea.
EOF

echo "scaffolded:"
echo "  $KNOWLEDGE/docs/specs/"
echo "  $KNOWLEDGE/docs/decisions/"
echo "  $KNOWLEDGE/ideas/"
echo "  $KNOWLEDGE/INDEX.md (stub)"

# ---------- 3. Detect monorepo ----------
MONO=""
for marker in pnpm-workspace.yaml go.work Cargo.toml; do
    if [[ -f "$REPO_ROOT/$marker" ]]; then
        MONO="$marker"
        break
    fi
done
if [[ -z "$MONO" ]] && [[ -d "$REPO_ROOT/packages" || -d "$REPO_ROOT/services" || -d "$REPO_ROOT/apps" ]]; then
    MONO="folder layout"
fi
if [[ -n "$MONO" ]]; then
    echo ""
    echo "monorepo detected ($MONO). Per-package subdirectories under specs/"
    echo "will be created on first /keep-compile that touches each package."
fi

# ---------- 4. Detect pre-existing docs (ingestion candidates) ----------
CANDIDATES=()
for path in README.md ARCHITECTURE.md DESIGN.md RUNBOOK.md; do
    [[ -f "$REPO_ROOT/$path" ]] && CANDIDATES+=("$REPO_ROOT/$path")
done
for d in docs doc documentation notes design-notes rfc rfcs adr decisions runbooks wiki .wiki; do
    if [[ -d "$REPO_ROOT/$d" ]]; then
        while IFS= read -r f; do
            CANDIDATES+=("$f")
        done < <(find "$REPO_ROOT/$d" -type f \( -name '*.md' -o -name '*.txt' -o -name '*.org' \) 2>/dev/null | head -50)
    fi
done

if [[ ${#CANDIDATES[@]} -gt 0 ]]; then
    echo ""
    echo "found ${#CANDIDATES[@]} candidate doc(s) for ingestion:"
    for c in "${CANDIDATES[@]:0:10}"; do
        echo "  $c"
    done
    if [[ ${#CANDIDATES[@]} -gt 10 ]]; then
        echo "  … and $((${#CANDIDATES[@]} - 10)) more"
    fi
    echo ""
    echo "next: run /keep-compile ./docs/ (or the relevant folder) to start"
    echo "      per-file approval-based migration."
fi

# ---------- 5. Append AGENTS.md / CLAUDE.md / .cursorrules snippet ----------
SNIPPET_TARGET=""
for f in AGENTS.md CLAUDE.md .cursorrules; do
    if [[ -f "$REPO_ROOT/$f" ]]; then
        SNIPPET_TARGET="$REPO_ROOT/$f"
        break
    fi
done
if [[ -z "$SNIPPET_TARGET" ]]; then
    SNIPPET_TARGET="$REPO_ROOT/AGENTS.md"
    touch "$SNIPPET_TARGET"
    echo ""
    echo "no AGENTS.md / CLAUDE.md / .cursorrules found — created AGENTS.md"
fi

if grep -q "## KEEP — Knowledge layer" "$SNIPPET_TARGET" 2>/dev/null; then
    echo ""
    echo "$SNIPPET_TARGET already contains the KEEP snippet — leaving it alone."
else
    cat >> "$SNIPPET_TARGET" <<'EOF'

## KEEP — Knowledge layer for this repository

`/knowledge/` is the authoritative source of truth for:
- WHAT this system does (specs)
- WHY it is built this way (ADRs)
- HOW it operates under failure (specs with tag `runbook`)
- WHERE components live and connect (specs with tag `architecture`)
- WHAT we've been thinking about but not yet committed to (ideas)

### Mandatory consultation before responding

Before answering ANY of these, run `/keep-ask <topic>` first:
- Questions about system behavior, design, or history
- Questions naming a feature, service, ADR, endpoint, or domain
- Requests to implement, modify, refactor, or remove existing behavior
- Any uncertainty about whether a decision or convention exists

If `/keep-ask` returns "no indexed knowledge", say so explicitly in your
answer — do NOT fall back to generic knowledge as if it were repo truth.

### After non-trivial code changes

Run `/keep-compile` before declaring the work done. A change that touches
behavior, architecture, or operations without updating `/knowledge` is
incomplete.

### Before merging

Run `/keep-check-drift` on the diff. Drift exit-code 1 blocks merge.

### Periodic

`/keep-govern` weekly for hygiene.

### Capture, don't drop

Half-formed ideas → `/keep-idea "..."`. Don't lose them in chat.
EOF
    echo ""
    echo "appended KEEP workflow snippet to $SNIPPET_TARGET"
fi

# ---------- 6. Final summary ----------
echo ""
echo "================================================================="
echo "KEEP scaffolding complete in $KNOWLEDGE"
echo ""
echo "Next steps:"
if [[ ${#CANDIDATES[@]} -gt 0 ]]; then
    echo "  1. /keep-compile ./docs/   # migrate pre-existing docs with per-file approval"
else
    echo "  1. /keep-idea \"...\"        # capture your first half-formed thought"
fi
echo "  2. /keep-ask <topic>       # consult /knowledge before non-trivial questions"
echo "  3. /keep-compile           # after non-trivial code changes"
echo "================================================================="
